name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Java 17 (Temurin distro)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Install Android SDK + build tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34           # or match your project's compileSdk
          build-tools: '34.0.0'   # match your actual Build Tools version

      # 4. Build the Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 5. Upload the Debug APK as an artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk